### ISSUE TITLE
ImportError: cannot import name 'wave' from 'cadqueryhelper'

### ISSUE THREAD

**Issue by mlewis-everley** [medicationforall/skirmishbunker#1]
Hi.

I have stumbled upon your libs and they look  really interesting! I have tried to set them up however and am getting the folowing error when  I try to run your example script:

---
Traceback (most recent call last):
  File "/home/user/Projects/cadquery/bunker-one.py", line 2, in <module>
    from skirmishbunker import Bunker
  File "/home/user/Projects/cadquery/lib/python3.10/site-packages/skirmishbunker/__init__.py", line 4, in <module>
    from .SplitDoor import SplitDoor
  File "/home/user/Projects/cadquery/lib/python3.10/site-packages/skirmishbunker/SplitDoor.py", line 3, in <module>
    from cadqueryhelper import shape, wave
ImportError: cannot import name 'wave' from 'cadqueryhelper' (/home/user/Projects/cadquery/lib/python3.10/site-packages/cadqueryhelper/__init__.py)
---

I have installed all the dependencies into a venv via pip, which I believe is the intention?

Python version I am running is 3.10 (if that helps).

Cheers,

Mo

**Comment by medicationforall** [comment]
@mlewis-everley Good catch, I'll get a fresh environment setup, and attempt to reproduce. 
It looks like I put out a newer release of [cadqueryhelper](https://github.com/medicationforall/cadqueryhelper/releases), referenced it in some existing code and forgot to update the version dependency in the [pyproject.toml](https://github.com/medicationforall/skirmishbunker/blob/main/pyproject.toml)

Thank you for the bug report! 
I'll update the issue again when I learn a bit more.

**Comment by medicationforall** [comment]
@mlewis-everley 
sweet!, error reproduced
``` bash
(bunkerbug) C:\Users\inkli\OneDrive\Desktop\test\skirmishbunker>python ./example/bunker3.py
Traceback (most recent call last):
  File "C:\Users\inkli\OneDrive\Desktop\test\skirmishbunker\example\bunker3.py", line 2, in <module>
    from skirmishbunker import Bunker
  File "C:\Users\inkli\Envs\bunkerbug\lib\site-packages\skirmishbunker\__init__.py", line 4, in <module>
    from .SplitDoor import SplitDoor
  File "C:\Users\inkli\Envs\bunkerbug\lib\site-packages\skirmishbunker\SplitDoor.py", line 3, in <module>
    from cadqueryhelper import shape, wave
ImportError: cannot import name 'wave' from 'cadqueryhelper' (C:\Users\inkli\Envs\bunkerbug\lib\site-packages\cadqueryhelper\__init__.py)
```
That's pretty much what I anticipated.

Installed the package locally and ran ./example/bunker3.py from the root directory to generate the stacktrace.

**Comment by mlewis-everley** [comment]
No probs, it looked to me like it might be some form of dependency version mismatch (I seem to spend a lot of time these days dealing with those in some way or other). 🙂

**Comment by mlewis-everley** [comment]
Oh, in the mean time, is it possible to switch to the latest version of cadqueryhelper (that has the correct imports) via pip?

**Comment by medicationforall** [comment]
@mlewis-everley Potentially, but it's not all doom and gloom.
I Just updated the [pyproject.toml](https://github.com/medicationforall/skirmishbunker/blob/main/pyproject.toml) and cut a new release of the skirmishbunker repo.

I'll try a fresh install again and hopefully that helps the problem

**Comment by medicationforall** [comment]
With the updated dependencies and running pip install I was able to to run an example script that was erroring prior.

In this case **[./example/bunker3.py](https://github.com/medicationforall/skirmishbunker/blob/main/example/bunker3.py)** ran correctly and generated a working stl.
![bunker3](https://github.com/medicationforall/skirmishbunker/assets/19323166/dad654f3-9a92-417c-bf4c-05f1c9f90a5f)

@mlewis-everley please update your code and attempt the install again

As an aside **pip install git+https://github.com/medicationforall/skirmishbunker** I believe will install the master branch (which I had broken)
and **pip install git+https://github.com/medicationforall/skirmishbunker@1.1.3** will install a locked version based on that release.

**Comment by mlewis-everley** [comment]
OK, thanks. So to clarify, I should be able to run `pip install -u https://github.com/medicationforall/skirmishbunker` (I don’t have loads of experience with Python and pip)

I will give it a try tomorrow 😁

**Comment by medicationforall** [comment]
@mlewis-everley yeah, however you installed it before please try again.

**Comment by mlewis-everley** [comment]
So I ran a `pip install -u https://github.com/medicationforall/skirmishbunker` and then ran the example script and have now got the following:

![bunker](https://github.com/medicationforall/skirmishbunker/assets/687143/2a055ee2-e98f-4790-8393-54669b0a5084)

Thanks so much for the assist! I will sign up for your Patreon once my bank can replace my card that they canceled without telling me :-(!
