### ISSUE TITLE
Pips and Magnets

### ISSUE THREAD

**Issue by mlewis-everley** [medicationforall/skirmishbunker#6]
So, in relation to comments in PR #5 I have noticed some issues with Pips and Magents

1. The holes generated for pips are quite snug, I can imagine over usage these would cause breaking of the pegs. It might be worth oversizing the holes a tiny bit, but should this be hardcoded or use some kind of multiplier that can be set?
2. When I use `render_magnets` it doesn't seem to do anything?

**Comment by medicationforall** [comment]
1. The pip oversize is going to vary by printer, all in all I'm ok with having some margin by default just not sure what the goldilocks zone is.

2. Try turning both flags on. Render_pips and render_magnets. 

The history of how the code got there is that; what works as a pip cutout in the roof, also works as a magnet cut out. When making the magnet cutout I only really need to make extra cutouts for the top of the bunker body.

In  practice what that means is I should have some **OR** logic if render_pip or render_magnets in some spots of the code.

**Comment by medicationforall** [comment]
@mlewis-everley this is getting resolved with your pull request.

**Comment by mlewis-everley** [comment]
Hopefully 😱
