### ISSUE TITLE
Creating a custom roof

### ISSUE THREAD

**Issue by mlewis-everley** [medicationforall/skirmishbunker#7]
Soooo,,, I tried messing about with the roof, but I think I want something a bit simpler... Maybe no railings and a chamfered edge? I think the default roof would require a lot of faff to achieve this, it might be easier to just swap in a new one, but I am not entirely sure the best way to do this.

Any thoughts?

**Comment by medicationforall** [comment]
This is a neat one. Totally doable with or without code changes. There are a Couple different ways it can be approached, and the solution will vary based on your requirements.

*Do you want to commit your alternate roof into the existing codebase?*

* If yes, than it can be a parameter to set what style of roof.
* If no, than we can talk about dependency injection, and how robust that feature needs to be.
---

In either case The files you want to get familiar with is:
* [bunkerRoof.py](https://github.com/medicationforall/skirmishbunker/blob/main/src/skirmishbunker/bunkerRoof.py)
  * This is the bunker mixin that instantiates the roof factory class
* [Roof.py](https://github.com/medicationforall/skirmishbunker/blob/main/src/skirmishbunker/Roof.py)
  * This is the current roof factory class 

---

## No Code change Option - replace the roof factory class.
* When the make lifecycle is called on the bunker it in turn calls *make_roof()* in [bunkerRoof.py](https://github.com/medicationforall/skirmishbunker/blob/main/src/skirmishbunker/bunkerRoof.py)
  * self.**roof_bp** is set after the *make_roof* call in bunkerRoof.py you can replace that variables value with whatever you want, as long as it has a build lifecycle.
  * Assuming you inject your own class with a build lifecycle and it returns something shape oriented that's compatible with cadquery my code won't know the difference.

code might look something like this
``` python
import cadquery as cq
from skirmishbunker import Bunker

bp = Bunker()
# your bunker parameters here ...
bp.make()

#intantiate your new roof class
new_roof_bp = MyRoofClass()
# set your own parameters custom to your roof here or alternatively pass in the bunker bp and your class can reference whatever properties from the parent that you want.
new_roof_bp.make()

bp.roof_bp = new_roof_bp
my_bunker = bp.build()
```

When you call bp.build() it will in turn run
``` python
def build_roof(self, z_translate=0):
        self.roof = self.roof_bp.build().translate((0, 0, z_translate))

        if self.roof_x_translate != None and self.roof_z_translate:
            print('build plate translate')
            self.roof = self.roof.translate((self.roof_x_translate,0,self.roof_z_translate))

        return self.roof
```

## speculative
Now that you've seen some of the guts of this thing there are all kinds of different options.
Instead of focusing attention **after** *bp.make()* is called; we could assign the roof class to a new *self.roof_class* parameter
when the bunker factory is instantiated default it to  *self.roof_class =  Roof* and prior to calling *make()* override  *self.roof_class = MyCustomRoofClass*.

Instead of having the parent describe the relationship to the child have the child pull the relationship out of the parent.

currently I have this:
``` python
def make_roof(self):
    length = self.length-(2*(self.inset-self.roof_overflow))
    width = self.width-(2*(self.inset-self.roof_overflow))

    print('roof length', length)
    print ('roof width', width)
    bp = Roof()
    bp.height = self.roof_height
    bp.length = length
    bp.width = width
    bp.inset = self.roof_inset
    bp.bunker_int_length = self.int_length
    bp.bunker_int_width = self.int_width

    bp.wall_details_inset = self.roof_wall_details_inset
    bp.render_floor_tiles = self.render_floor_tiles
    bp.render_hatches = self.render_ladders
    bp.hatch_panels = self.ladder_panels

    bp.panel_length = self.panel_length
    bp.panel_width = self.panel_width
    bp.panel_padding = self.panel_padding

    bp.render_pips = self.render_pips
    bp.pip_radius = self.pip_radius
    bp.pip_height = self.pip_height
    bp.pip_padding = self.pip_padding

    bp.roof_overflow = self.roof_overflow
    bp.make()
    self.roof_bp = bp
```

I think what would be preferrable is:
``` python
def make_roof(self):
    length = self.length-(2*(self.inset-self.roof_overflow))
    width = self.width-(2*(self.inset-self.roof_overflow))

    print('roof length', length)
    print ('roof width', width)
    bp = self.roof_class()
    bp.length = length
    bp.width = width 
    bp.init_from_parent(self)
    bp.make()
    self.roof_bp = bp
```

the bp.init_from_parent(self) is speculative, the parent could be passed in on the constructor, I just wouldn't make it a required field. Anyways the contract would change from the parent telling the child what it's paremeter defaults should be to the child asking the parent do you have parameter_x? and defaulting it's values based on what the parent has available. 

---

So that's an information dump, and I hope some of it makes sense. 
I tried to make overall structure of the framework relatively loose and not too rigid. It's intentionally small with only two lifecycles. 

@mlewis-everley What are your thoughts?

**Comment by mlewis-everley** [comment]
I am fine with committing directly to the repo, looking at your docs, might be cool to have some form of base roof class that can be expanded upon to create fancy roofs (like the current default).

I guess dependency injection is the best way to handle that? I think that might be a bit beyond my Python ability at the moment though...

**Comment by medicationforall** [comment]
Test in isolation, look at the existing [roof class](https://github.com/medicationforall/skirmishbunker/blob/main/src/skirmishbunker/Roof.py) and  see if you can come close to a new class that does roughly what you want.

This is an example of the existing roof class being instantiated independent to the bunker itself.  
https://github.com/medicationforall/skirmishbunker/blob/main/example/roof.py

I don't know if you've seen it yet but this write up should give you a pretty thorough understanding of the bunker and how things shook out to the way they are.
https://github.com/medicationforall/skirmishbunker/blob/main/documentation/README.md

Helpful links, for your cadquery journey:
* Official
  * [Cadquery Documentation](https://cadquery.readthedocs.io/en/latest/)
    * [CadQuery Concepts](https://cadquery.readthedocs.io/en/latest/primer.html)
    *  [CadQuery Design Principles](https://cadquery.readthedocs.io/en/latest/designprinciples.html)
* References I wrote 
  * [Cadquery Workplane and the Stack](https://gist.github.com/medicationforall/ecb256d1f37a0c64ba4eac9d0f80e3fe)
  * [CadQuery Shape primitives](https://gist.github.com/medicationforall/18b31e0858fe8abf0c3432c8d3b8f9e7)
* These other repo's may be helpful as well
  * [cadqueryhelper](https://github.com/medicationforall/cadqueryhelper)
  * [cqterrain](https://github.com/medicationforall/cqterrain)
  * [cqindustry](https://github.com/medicationforall/cqindustry)

---

Once you get a roof you want to try (doesn't have to be final), I can help you working out how to integrate it.

**Comment by mlewis-everley** [comment]
Yes I have read the docs and been through Roof.py. The tricky part is trying to pick out what I want to keep! It will probably easier to start again and try to splice the hatch and tiles on top of it :-/.

As a very quick example, I am thinking of adding something like the following, but also render peg/magnet holes, hatch and tiles:

![bunker-simple-roof](https://github.com/medicationforall/skirmishbunker/assets/687143/71231480-35f9-4c68-9c90-02ba4d792cde)

I am thinking the chamfer will probably inherit from the new property I added, but like I said above, the tiles, hatch and peg/magnet holes need to be positioned correctly.

**Comment by medicationforall** [comment]
@mlewis-everley That gives me enough to get started, if your ok with it I'll get a baseline class going and you can modify it to suit your needs.

**Comment by mlewis-everley** [comment]
So I had a play about this, I took your base roof and stripped out what I thought wasn't needed and did a test render:

![bunker-simple-roof-2](https://github.com/medicationforall/skirmishbunker/assets/687143/9cdda0ba-e390-41b3-a279-a03fda5734cf)

I uploaded a gist here: https://gist.github.com/mlewis-everley/313eadca096e96753b552e6167620ea8

**Comment by mlewis-everley** [comment]
I just quickly updated the gist to add additional chamfers (to match the base):

![bunker-simple-roof-3](https://github.com/medicationforall/skirmishbunker/assets/687143/c94927b4-ad59-41a6-9a98-a331c77d2d8f)

It would be great if there was a way to align the hatch to whatever tile it is overlapping, but I am not sure how you would do that...

**Comment by medicationforall** [comment]
@mlewis-everley Noice!

Check out this commit. 
https://github.com/medicationforall/skirmishbunker/commit/f7b4aba8d61e24c202eee7ee71097de788ca5ea2
I put in a bit of thought as far as edge cases that have bit me in the past for making chamfers / fillets. It throws some additional exceptions.

All in all my code isn't doing a whole lot. 
I called mine FlatRoof but the name doesn't really matter we can rename it.

My suggestion is merge your gist with what I put in place.

I want to refactor the individual tile generation to use this code
* https://github.com/medicationforall/cqterrain/blob/main/documentation/tile.md#slot-diagonal
* https://github.com/medicationforall/cqterrain/blob/main/src/cqterrain/tile/slotDiagonal.py
* https://github.com/medicationforall/cqterrain/blob/main/example/tile/slot_diagonal.py
Import it from cqterrain and plug the parameters in.

For the most part your gist should work great and can replace my implementation. Just the tile generation will come from a different place (not just targeting your roof, the other roof is going to get updated as well), and I think I want to keep some of the exception edge cases.

**Comment by mlewis-everley** [comment]
Doing some work on merging the two code bases at the moment. In the mean time, did a quick print of the new roof:

![IMG_20230706_212006.jpg](https://github.com/medicationforall/skirmishbunker/assets/687143/0598744b-8b94-48f6-9c06-a593a686d8ec)

![IMG_20230706_212024.jpg](https://github.com/medicationforall/skirmishbunker/assets/687143/6ca2805b-a7bb-4e7b-a04d-d7e8a944a17c)

There were some issues, but I am pretty happy with the result 🙂

**Comment by medicationforall** [comment]
@mlewis-everley That's Great!
your layer lines look good.

If you do have boo boo's that need fixing; I've had good results using wood filler to fill gaps.
https://miniforall.com/smoothingprints.html

**Comment by mlewis-everley** [comment]
OK, so I have just pushed an update to my fork. It re-adds tile supports but with some updates:

1. I made the slots on the tiles cut through the whole tile. This should reduce filament usage a tiny amount but also helps with point 2.
2. I have added the ability to "cut" tiles into the roof (if you set a negative offset). This gives it more of an industrial "stamped metal" look than tiles welded on, so thought it was a cool option.
3. I have made tile and slot size calculation done entirely via maths/percentages. This means you can have lots of funky tile sizes :-)
4. I have also moved calculations and duplicate code into helper methods. If you are thinking of dependency injection ongoing then these make the creation of custom hot swappable elements a lot easier.

## New Roof Tiles (based on percentages):
![bunker-roof-tile-18](https://github.com/medicationforall/skirmishbunker/assets/687143/54b88d88-c5ac-4d8d-b26d-74ea7115d034)

## New Roof Tile Cuts
![bunker-roof-tile-cut](https://github.com/medicationforall/skirmishbunker/assets/687143/7e4d7e10-b20d-4052-be96-a54eac22cd7d)

My fork is: https://github.com/mlewis-everley/skirmishbunker/blob/main/src/skirmishbunker/FlatRoof.py

**Comment by mlewis-everley** [comment]
> @mlewis-everley That's Great! your layer lines look good.
> 
> If you do have boo boo's that need fixing; I've had good results using wood filler to fill gaps. https://miniforall.com/smoothingprints.html

You can also use marble dust (from painting/hobby shops). It is a little more expensive, but can work quite nicely.

**Comment by medicationforall** [comment]
@mlewis-everley 
https://github.com/mlewis-everley/skirmishbunker/blob/main/src/skirmishbunker/FlatRoof.py

That looks great!

``` python
# Not entirely sure why -1 works here...
        if cut_tiles == True:
```

Python has the concept of Truthy and Falsy values. 
https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/

**Comment by mlewis-everley** [comment]
> 

I think that comment didn't survive a code refactoring! For some reason the tiles are ~1mm too far above the roof when translated and I couldn't work out why (possibly because the roof isn't sitting on the z, but is half way along the z instead)?

**Comment by mlewis-everley** [comment]
I have had a crazy few days, but I managed to put a bit more work into this project. I have now re-added magnet/pip holes to my branch and also fixed the tiles so they should scale properly at different heights.

I just want to re-add the hatches and then I will open a PR.

**Comment by medicationforall** [comment]
All good, I understand.
I appreciate all the work you've already done!

**Comment by mlewis-everley** [comment]
No probs, it's been quite fun doing CAD via programming 😁.

One thing I noticed, your terrain library has several different tile types (including the ones you use on the roof). Wouldn't it make more sense to use those tiles (instead of re-creating them)? You could also swap them out too.

**Comment by medicationforall** [comment]
You are correct!
It does make more sense, and is a point on my refactor / todo list.

**Comment by mlewis-everley** [comment]
Cool, might be a nice future update 😁.

Just letting you know, there is a fairly hefty pull request coming in the next few days. I have made the roof with railings inherit from FlatRoof and refactored a lot of the roof code. I have tried to retain backwards compatibility where possible, but this might be a more major release…

**Comment by medicationforall** [comment]
Awesome! I look forward to it.

**Comment by medicationforall** [comment]
Closing this one I'm going to open a new issue and tag you @mlewis-everley  in  it
