### ISSUE TITLE
2.0.0 Discussion Items

### ISSUE THREAD

**Issue by medicationforall** [medicationforall/skirmishbunker#9]
@mlewis-everley 

I did some stuff, probably worth looking at the release notes.

### Contributed By Morven Lewis-Everley
* Updated flat roof to use hatches and tiles.
* Migrate Roof to Detailed roof, make it inherit from FlatRoof and refactor how tiles, hatches and magnet holes are generated.
* Introduce a helper class that assist in generation of a Series of shapes (as all series code seems to be 90% duplication with only a few changes).
* Added basic dependency injection for swapping out roof type on the fly.
* Added the ability to customise the hatches when generating the roof and the bunker together.
* Added an example of swapping out the roof.

### Cleanup
* Added Apache 2 license to top of source files.
* Restored cut hatch code.
* Restored tile generation code for detailed roof.
  * this was due to a regression bug.
  * temp hack for now
* Fix parameter order when making pip / magnet holes in the roof.
* Make Calc methods protected
* Brought back the render_hatches flag
* Added the render_hatch_cuts flag
* FlatRoof changed hole_diameter to hole_radius
* Added Bunker 5 example.
* Added Bunker 6 example.

---

I added @todo code comments.

[bunkerRoof.py](https://github.com/medicationforall/skirmishbunker/blob/35414f8872552010900a6b46584b96f489dc4f35/src/skirmishbunker/bunkerRoof.py#L57-L59)
``` python
    #@todo discussion point - this is where we potentially set a boolean feature flag for whether the roof should abide by interior dimensions
    bp.bunker_int_length = self.int_length
    bp.bunker_int_width = self.int_width
```

Those parameters inform the roof what the internal dimensions of the bunker room is.
When attempting to line up the ladder to the hatch having the internal dimensions makes that possible.
Instead of assuming the values are present the functionality could possibly be enabled by a boolean feature flag.

---

[DetailedRoof.py](https://github.com/medicationforall/skirmishbunker/blob/main/src/skirmishbunker/DetailedRoof.py#L182-L204)
``` python
    #@todo discussion point - this is a hack until I can figure out why the FlatRoof tile generator created different results.
    def _make_tiles(self):
        tile_size = 21
        tile_padding = 2
        tile_height = self.tile_height

        int_length = self.length-(2*(self.inset+self.wall_width))
        int_width = self.width-(2*(self.inset+self.wall_width))

        tile = cq.Workplane("XY").box(tile_size, tile_size, tile_height)
        slot = cq.Workplane("XY").slot2D(tile_size,2).extrude(tile_height).rotate((0,0,1),(0,0,0),45)
        slot2 = cq.Workplane("XY").slot2D(tile_size-7,2).extrude(tile_height).rotate((0,0,1),(0,0,0),45).translate((-3,-3,0))
        slot3 = cq.Workplane("XY").slot2D(tile_size-7,2).extrude(tile_height).rotate((0,0,1),(0,0,0),45).translate((3,3,0))
        slot4 = cq.Workplane("XY").slot2D(tile_size-7-7,2).extrude(tile_height).rotate((0,0,1),(0,0,0),45).translate((-3-3,-3-3,0))
        slot5 = cq.Workplane("XY").slot2D(tile_size-7-7,2).extrude(tile_height).rotate((0,0,1),(0,0,0),45).translate((3+3,3+3,0))
        tile = tile.cut(slot).cut(slot2).cut(slot3).cut(slot4).cut(slot5)

        columns = math_floor(int_width/(tile_size + tile_padding))
        rows = math_floor(int_length/(tile_size + tile_padding))
        tile_grid = grid.make_grid(part=tile, dim = [tile_size + tile_padding, tile_size + tile_padding], columns = columns, rows = rows)

        self.tiles = tile_grid.translate((0,0,self._calc_tile_z_translate()))
```

The new tile generator code in FlatRoof.py broke my original reference bunker. I put this one in place to get the tiles working again.
My intention is to investigate further what FlatRoof.py is doing and come up with some sort of compromise.

---

## Bunker Examples

I Added [Bunker 5 example](https://github.com/medicationforall/skirmishbunker/blob/main/example/bunker5_chamfer_flat_roof.py)

![test5_chamfer_bunker](https://github.com/medicationforall/skirmishbunker/assets/19323166/27359f17-ec87-46fb-a6b3-d93f96d17abe)

* This needs it's cut out hatch fixed
  * Right now it's dependent on wall_width which for the flat roof is zero in the context of a flatRoof should use height + tile_height
* The roof chamfer corners I didn't figure out in the time I had. 
  * the code may be missing, Or I'm lacking some knowledge.
* I'm not quite sure why the roof_overflow needed to be set to what it was in order to make to roof flush.
  * bp.roof_overflow = -3
* It seems like the pip / magnet cutouts could be aware of the corner_chamfers as opposed to setting pip_padding to account for the difference

I also added my reference bunker as [test 6 example.](https://github.com/medicationforall/skirmishbunker/blob/main/example/bunker6_test_for_drift.py) 
This is what I was checking against to make sure the new code was working as anticipated.

![test6_bunker](https://github.com/medicationforall/skirmishbunker/assets/19323166/72e291cf-053d-4de9-823a-a4ca9ca3b1a7)

---

That's enough trouble for now.

**Comment by mlewis-everley** [comment]
Do you think you could cut this one issue up into several smaller issues? Otherwise this trail could get very long and a bit convoluted 🤯

**Comment by medicationforall** [comment]
sure

**Comment by mlewis-everley** [comment]
So as per PR #15 I have updated the Bunker5 example to add corner chamfers to the roof and also tweaked the roof tiles so they fit on the roof a little better :-)

![bunker5](https://github.com/medicationforall/skirmishbunker/assets/687143/af61d2c2-dff0-4a37-8a77-63f028181be2)

**Comment by medicationforall** [comment]
sweet!
